Description: >
  Capstone project for Cloud DevOps Engineering Nanodegree
  Author - Sabbir Hossain

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String

  SourceIP:
    Description: Ip address to allow SSH access to the bastion host
    Type: String
    Default: IP/32

  JenkinsImageID:
    Description: An image ID for EC2 Instance
    Type: String

  KeyJenkinsSSH:
    Description: KeyName to access jenkins host
    Type: "AWS::EC2::KeyPair::KeyName"

Resources:
  CapstoneSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to ec2 and SHH access
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-WASG

  CapstoneEc2:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update
          sudo apt install -y default-jdk
          sudo apt-get install nginx
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          sudo apt-get update
          sudo apt-get install -y jenkins
          sudo apt-get install -y tidy
          sudo systemctl status jenkins
      SecurityGroupIds:
        - Ref: CapstoneSG
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: "10"
            DeleteOnTermination: true
            VolumeType: "gp2"
      ImageId: !Ref JenkinsImageID
      InstanceType: t3.small
      KeyName: !Ref KeyJenkinsSSH
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-JenkinsInstance"

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

  EIPAssociation0:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - CapstoneEc2
      - EIP
    Properties:
      InstanceId:
        Ref: CapstoneEc2
      AllocationId:
        Fn::GetAtt:
          - EIP
          - AllocationId

Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Join ["", ["http://", !GetAtt "CapstoneEc2.PublicDnsName", ":8080"]]
